#!/usr/bin/env python3

def build(bld):
    vehicle = bld.path.name
    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AC_AttitudeControl',
            'AC_PID',
            'AP_Motors',
            'AP_Rocket',
            # The rocket needs none of the following, but shared library code
            # (GCS_Common.cpp, RC_Channel.cpp) references them unconditionally
            # and will not link without them.
            'AP_AdvancedFailsafe',
            'AP_Avoidance',
            'AP_LTM_Telem',
            'AP_Devo_Telem',
            'AP_KDECAN',
        ],
    )

    bld.ap_program(
        program_name='rocket',
        program_groups=['bin', 'rocket'],
        use=vehicle + '_libs',
        )
