function bytes = rocket_json_encode(t, gyro, accel_body, pos_ned, quat, vel_ned) %#codegen
% ROCKET_JSON_ENCODE  Sensor state -> JSON reply bytes for SITL (--model JSON).
%
% MATLAB Function block that builds the reply ArduPilot's JSON backend expects, in the
% exact form the script bridge (rocket_sim.m) sends. Two things SIM_JSON is strict about:
%
%   - Wrap the JSON in NEWLINES ("\n{...}\n"). SIM_JSON converts '\n' to nul and parses
%     between the last two nuls; a message with no leading newline is silently dropped.
%   - accel_body is SPECIFIC FORCE -- thrust and aero only, gravity EXCLUDED. A
%     stationary vertical rocket reads about +9.81 on the nose axis, not zero.
%
% Required fields: timestamp, imu.gyro, imu.accel_body, velocity (NED), and one of
% attitude/quaternion (here: quaternion [w x y z]). Wire the output to a UDP Send block.
%
% NOTE: variable-length char/uint8 output is fine in NORMAL (interpreted) simulation,
% which is what a UDP-in-the-loop model uses. It is NOT code-generation friendly; do not
% try to build this block to C.

s = sprintf(['{"timestamp":%.6f,' ...
             '"imu":{"gyro":[%.6f,%.6f,%.6f],"accel_body":[%.6f,%.6f,%.6f]},' ...
             '"position":[%.6f,%.6f,%.6f],' ...
             '"quaternion":[%.8f,%.8f,%.8f,%.8f],' ...
             '"velocity":[%.6f,%.6f,%.6f]}'], ...
            t, ...
            gyro(1), gyro(2), gyro(3), ...
            accel_body(1), accel_body(2), accel_body(3), ...
            pos_ned(1), pos_ned(2), pos_ned(3), ...
            quat(1), quat(2), quat(3), quat(4), ...
            vel_ned(1), vel_ned(2), vel_ned(3));

bytes = [uint8(10), uint8(s), uint8(10)];
end
